export const CLEAR_ORDER = 'CLEAR_ORDER';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const MANUAL_ADD_ITEM = 'MANUAL_ADD_ITEM';
export const SET_ORDER = 'SET_ORDER';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const IMPORT_INVENTORY = 'IMPORT_INVENTORY';
export const FILE_UPLOAD_INIT = 'FILE_UPLOAD_INIT';
export const FILE_LOADED = 'FILE_LOADED';
export const FILE_UPLOAD_PENDING = 'FILE_UPLOAD_PENDING';
export const FILE_UPLOAD_SUCESS = 'FILE_UPLOAD_SUCESS';
export const FILE_UPLOAD_FAIL = 'FILE_UPLOAD_FAIL';
export const FILES_UPLOADED_COMPLETE = 'FILES_UPLOADED_COMPLETE';